class AppText {
  static Map<String, Map<String, String>> values = {
    "fr": {
      "home": "Accueil",
      "scan": "Scanner",
      "history": "Historique",
      "settings": "Paramètres",
      "start": "Commencer le scan",
      "app_name": "Scan AI",
      "camera": "Caméra",
      "gallery": "Galerie",
      "translate": "Traduire",
      "translation": "Traduction",
      "language_label": "Langue",
      "no_history": "Aucun historique",
      "change_theme": "Changer thème",
      "settings_title": "Paramètres",
      "settings_header": "Paramètres",
      "daily_reminder_title": "Rappel quotidien",
      "daily_reminder_body":
          "N'oubliez pas d'utiliser Smart Scanner AI aujourd'hui.",
      "home_header_title": "Scan AI",
      "home_objective": "Objectif",
      "home_description":
          "Cette application intelligente permet de scanner une image, extraire le texte, le traduire et le lire à voix haute.",
      "features_title": "Fonctionnalités",
      "feature_import_image": "Importer une image",
      "feature_text_recognition": "OCR Texte",
      "feature_language_detection": "Détection langue",
      "feature_speech": "Lecture vocale",
      "test_notification_now": "Tester notification maintenant",
      "language_setting": "Langue",
      "dark_mode": "Mode sombre",
      "feedback_sound": "Sons de feedback",
      "feedback_enabled": "Activer sons et vibrations",
      "auth_login": "Se connecter",
      "auth_signup": "Créer un compte",
      "auth_login_subtitle": "Connectez-vous pour continuer",
      "auth_signup_subtitle": "Créez votre compte",
      "auth_email": "Email",
      "auth_password": "Mot de passe",
      "auth_name": "Nom complet",
      "auth_forgot_password": "Mot de passe oublié ?",
      "auth_no_account": "Pas de compte ?",
      "auth_have_account": "Déjà un compte ?",
      "auth_email_required": "Veuillez entrer votre email",
      "auth_password_required": "Veuillez entrer votre mot de passe",
      "auth_name_required": "Veuillez entrer votre nom",
      "auth_error_user_not_found": "Aucun compte trouvé avec cet email",
      "auth_error_wrong_password": "Mot de passe incorrect",
      "auth_error_email_in_use": "Cet email est déjà utilisé",
      "auth_error_weak_password": "Le mot de passe doit contenir au moins 6 caractères",
      "auth_error_invalid_email": "Email invalide",
      "auth_error_invalid_credential": "Identifiants incorrects",
      "auth_error_generic": "Une erreur est survenue. Réessayez.",
      "auth_enter_email_reset": "Entrez votre email d'abord",
      "auth_reset_sent": "Email de réinitialisation envoyé",
      "auth_logout": "Se déconnecter",
      "auth_profile": "Profil",
      "auth_profile_title": "Mon Profil",
      "auth_member_since": "Membre depuis",
    },
    "en": {
      "home": "Home",
      "scan": "Scan",
      "history": "History",
      "settings": "Settings",
      "start": "Start Scan",
      "app_name": "Scan AI",
      "camera": "Camera",
      "gallery": "Gallery",
      "translate": "Translate",
      "translation": "Translation",
      "language_label": "Language",
      "no_history": "No history",
      "change_theme": "Change theme",
      "settings_title": "Settings",
      "settings_header": "Settings",
      "daily_reminder_title": "Daily reminder",
      "daily_reminder_body": "Don't forget to use Smart Scanner AI today.",
      "home_header_title": "Scan AI",
      "home_objective": "Goal",
      "home_description":
          "A smart app to scan images, extract text, translate and read aloud.",
      "features_title": "Features",
      "feature_import_image": "Import image",
      "feature_text_recognition": "Text recognition",
      "feature_language_detection": "Language detection",
      "feature_speech": "Speech",
      "test_notification_now": "Test notification now",
      "language_setting": "Language",
      "dark_mode": "Dark mode",
      "feedback_sound": "Feedback sounds",
      "feedback_enabled": "Enable sounds and vibrations",
      "auth_login": "Log in",
      "auth_signup": "Sign up",
      "auth_login_subtitle": "Sign in to continue",
      "auth_signup_subtitle": "Create your account",
      "auth_email": "Email",
      "auth_password": "Password",
      "auth_name": "Full name",
      "auth_forgot_password": "Forgot password?",
      "auth_no_account": "No account?",
      "auth_have_account": "Already have an account?",
      "auth_email_required": "Please enter your email",
      "auth_password_required": "Please enter your password",
      "auth_name_required": "Please enter your name",
      "auth_error_user_not_found": "No account found with this email",
      "auth_error_wrong_password": "Incorrect password",
      "auth_error_email_in_use": "This email is already in use",
      "auth_error_weak_password": "Password must be at least 6 characters",
      "auth_error_invalid_email": "Invalid email",
      "auth_error_invalid_credential": "Invalid credentials",
      "auth_error_generic": "An error occurred. Please try again.",
      "auth_enter_email_reset": "Enter your email first",
      "auth_reset_sent": "Password reset email sent",
      "auth_logout": "Log out",
      "auth_profile": "Profile",
      "auth_profile_title": "My Profile",
      "auth_member_since": "Member since",
    },
    "ar": {
      "home": "الرئيسية",
      "scan": "مسح",
      "history": "السجل",
      "settings": "الإعدادات",
      "start": "ابدأ المسح",
      "app_name": "Scan AI",
      "camera": "الكاميرا",
      "gallery": "المعرض",
      "translate": "ترجمة",
      "translation": "الترجمة",
      "language_label": "اللغة",
      "no_history": "لا يوجد سجل",
      "change_theme": "تغيير النمط",
      "settings_title": "الإعدادات",
      "settings_header": "الإعدادات",
      "daily_reminder_title": "تذكير يومي",
      "daily_reminder_body": "لا تنس استخدام Smart Scanner AI اليوم.",
      "home_header_title": "Scan AI",
      "home_objective": "الهدف",
      "home_description": "تطبيق ذكي لمسح الصور واستخراج النص وترجمته وقراءته",
      "features_title": "الميزات",
      "feature_import_image": "استيراد صورة",
      "feature_text_recognition": "استخراج النص",
      "feature_language_detection": "تحديد اللغة",
      "feature_speech": "قراءة صوتية",
      "test_notification_now": "اختبار الإشعار الآن",
      "language_setting": "اللغة",
      "dark_mode": "الوضع الداكن",
      "feedback_sound": "أصوات التفاعل",
      "feedback_enabled": "تفعيل الصوت والاهتزاز",
      "auth_login": "تسجيل الدخول",
      "auth_signup": "إنشاء حساب",
      "auth_login_subtitle": "سجل الدخول للمتابعة",
      "auth_signup_subtitle": "أنشئ حسابك",
      "auth_email": "البريد الإلكتروني",
      "auth_password": "كلمة المرور",
      "auth_name": "الاسم الكامل",
      "auth_forgot_password": "نسيت كلمة المرور؟",
      "auth_no_account": "ليس لديك حساب؟",
      "auth_have_account": "لديك حساب بالفعل؟",
      "auth_email_required": "يرجى إدخال بريدك الإلكتروني",
      "auth_password_required": "يرجى إدخال كلمة المرور",
      "auth_name_required": "يرجى إدخال اسمك",
      "auth_error_user_not_found": "لم يتم العثور على حساب بهذا البريد",
      "auth_error_wrong_password": "كلمة المرور غير صحيحة",
      "auth_error_email_in_use": "هذا البريد مستخدم بالفعل",
      "auth_error_weak_password": "يجب أن تحتوي كلمة المرور على 6 أحرف على الأقل",
      "auth_error_invalid_email": "بريد إلكتروني غير صالح",
      "auth_error_invalid_credential": "بيانات الاعتماد غير صحيحة",
      "auth_error_generic": "حدث خطأ. حاول مرة أخرى.",
      "auth_enter_email_reset": "أدخل بريدك الإلكتروني أولاً",
      "auth_reset_sent": "تم إرسال بريد إعادة تعيين كلمة المرور",
      "auth_logout": "تسجيل الخروج",
      "auth_profile": "الملف الشخصي",
      "auth_profile_title": "ملفي الشخصي",
      "auth_member_since": "عضو منذ",
    },
  };

  static String get(String lang, String key) {
    return values[lang]?[key] ?? key;
  }
}
