class AppText {
  static Map<String, Map<String, String>> values = {
    "fr": {
      "home": "Accueil",
      "scan": "Scanner",
      "history": "Historique",
      "settings": "Paramètres",
      "start": "Commencer le scan",
      "app_name": "Scan AI",
      "camera": "Caméra",
      "gallery": "Galerie",
      "translate": "Traduire",
      "translation": "Traduction",
      "language_label": "Langue",
      "no_history": "Aucun historique",
      "change_theme": "Changer thème",
      "settings_title": "Paramètres",
      "settings_header": "Paramètres",
      "daily_reminder_title": "Rappel quotidien",
      "daily_reminder_body":
          "N'oubliez pas d'utiliser Smart Scanner AI aujourd'hui.",
      "home_header_title": "Scan AI",
      "home_objective": "Objectif",
      "home_description":
          "Cette application intelligente permet de scanner une image, extraire le texte, le traduire et le lire à voix haute.",
      "features_title": "Fonctionnalités",
      "feature_import_image": "Importer une image",
      "feature_text_recognition": "OCR Texte",
      "feature_language_detection": "Détection langue",
      "feature_speech": "Lecture vocale",
      "test_notification_now": "Tester notification maintenant",
      "language_setting": "Langue",
      "dark_mode": "Mode sombre",
      "feedback_sound": "Sons de feedback",
      "feedback_enabled": "Activer sons et vibrations",
    },
    "en": {
      "home": "Home",
      "scan": "Scan",
      "history": "History",
      "settings": "Settings",
      "start": "Start Scan",
      "app_name": "Scan AI",
      "camera": "Camera",
      "gallery": "Gallery",
      "translate": "Translate",
      "translation": "Translation",
      "language_label": "Language",
      "no_history": "No history",
      "change_theme": "Change theme",
      "settings_title": "Settings",
      "settings_header": "Settings",
      "daily_reminder_title": "Daily reminder",
      "daily_reminder_body": "Don't forget to use Smart Scanner AI today.",
      "home_header_title": "Scan AI",
      "home_objective": "Goal",
      "home_description":
          "A smart app to scan images, extract text, translate and read aloud.",
      "features_title": "Features",
      "feature_import_image": "Import image",
      "feature_text_recognition": "Text recognition",
      "feature_language_detection": "Language detection",
      "feature_speech": "Speech",
      "test_notification_now": "Test notification now",
      "language_setting": "Language",
      "dark_mode": "Dark mode",
      "feedback_sound": "Feedback sounds",
      "feedback_enabled": "Enable sounds and vibrations",
    },
    "ar": {
      "home": "الرئيسية",
      "scan": "مسح",
      "history": "السجل",
      "settings": "الإعدادات",
      "start": "ابدأ المسح",
      "app_name": "Scan AI",
      "camera": "الكاميرا",
      "gallery": "المعرض",
      "translate": "ترجمة",
      "translation": "الترجمة",
      "language_label": "اللغة",
      "no_history": "لا يوجد سجل",
      "change_theme": "تغيير النمط",
      "settings_title": "الإعدادات",
      "settings_header": "الإعدادات",
      "daily_reminder_title": "تذكير يومي",
      "daily_reminder_body": "لا تنس استخدام Smart Scanner AI اليوم.",
      "home_header_title": "Scan AI",
      "home_objective": "الهدف",
      "home_description": "تطبيق ذكي لمسح الصور واستخراج النص وترجمته وقراءته",
      "features_title": "الميزات",
      "feature_import_image": "استيراد صورة",
      "feature_text_recognition": "استخراج النص",
      "feature_language_detection": "تحديد اللغة",
      "feature_speech": "قراءة صوتية",
      "test_notification_now": "اختبار الإشعار الآن",
      "language_setting": "اللغة",
      "dark_mode": "الوضع الداكن",
      "feedback_sound": "أصوات التفاعل",
      "feedback_enabled": "تفعيل الصوت والاهتزاز",
    },
  };

  static String get(String lang, String key) {
    return values[lang]?[key] ?? key;
  }
}
